import type { TriageDecisionDisplay } from "@/types";

export const mockDecisions: TriageDecisionDisplay[] = [
	{
		id: "1",
		fromName: "Sarah Johnson",
		fromEmail: "sarah@example.com",
		subject: "Where is my order #12345?",
		classification: "routine",
		confidence: 0.94,
		action: "auto_reply",
		reasoning:
			"Standard order status inquiry. The customer is asking about shipping status for order #12345. This is a routine question that can be answered with tracking information.",
		timeAgo: "2 min ago",
		createdAt: "2026-07-08T10:00:00Z",
		isTest: true,
	},
	{
		id: "2",
		fromName: "Mike Chen",
		fromEmail: "mike@example.com",
		subject: "URGENT: Product defective on arrival",
		classification: "urgent",
		confidence: 0.88,
		action: "escalate",
		priority: "urgent",
		escalationStatus: "pending",
		reasoning:
			"Product defect claim with urgent language. The customer reports a damaged product. High-priority escalation per escalation rules matching 'urgent' keyword.",
		timeAgo: "15 min ago",
		createdAt: "2026-07-08T09:47:00Z",
		isTest: true,
	},
	{
		id: "3",
		fromName: "Emily Davis",
		fromEmail: "emily@example.com",
		subject: "Question about your API documentation",
		classification: "technical",
		confidence: 0.76,
		action: "auto_reply",
		reasoning:
			"Technical question about API documentation. The customer is asking about endpoint authentication. Moderate confidence — directed to API docs.",
		timeAgo: "1 hour ago",
		createdAt: "2026-07-08T08:30:00Z",
		isTest: true,
	},
	{
		id: "4",
		fromName: "James Wilson",
		fromEmail: "james@example.com",
		subject: "Interested in bulk pricing for my team",
		classification: "sales",
		confidence: 0.82,
		action: "auto_reply",
		reasoning:
			"Sales inquiry about bulk pricing. The customer is interested in team pricing. Routine sales question with standard pricing available.",
		timeAgo: "3 hours ago",
		createdAt: "2026-07-08T07:15:00Z",
		isTest: true,
	},
	{
		id: "5",
		fromName: "Lisa Thompson",
		fromEmail: "lisa@example.com",
		subject: "I want a full refund — product not as described",
		classification: "urgent",
		confidence: 0.65,
		action: "escalate",
		priority: "high",
		escalationStatus: "pending",
		reasoning:
			"Refund request with low confidence. The customer is demanding a full refund claiming the product was not as described. Escalated per refund rule (high priority) and low confidence threshold.",
		timeAgo: "5 hours ago",
		createdAt: "2026-07-08T05:00:00Z",
		isTest: true,
	},
	{
		id: "6",
		fromName: "Alex Rivera",
		fromEmail: "alex@example.com",
		subject: "Thanks for the quick response!",
		classification: "other",
		confidence: 0.91,
		action: "auto_reply",
		reasoning:
			"Positive feedback email. The customer is thanking support for quick assistance. No action needed — auto-replied with a thank-you message.",
		timeAgo: "1 day ago",
		createdAt: "2026-07-07T14:20:00Z",
		isTest: true,
	},
];
